eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
server:
  port: 8665
spring:
  application:
    name: service-feign
feign:
  hystrix: #开启熔断机制 防止雪崩
    enabled: true  